### ISSUE TITLE
Buypass endpoint: 'MergeCertificate' failed: Unexpected response status code [NotFound] for [GetOrderDetailsAsync]

### ISSUE THREAD

**Issue by NikolaiKleppe** [shibayan/keyvault-acmebot#343] opened 2021-07-30 13:08 UTC
Hello,

Just deployed the service and configured it with the "https://api.buypass.com/acme/" ACME endpoint.

When executing /add-certificate I get this error.
"Unexpected response status code [NotFound] for [GetOrderDetailsAsync]" at the bottom.

In AppInsights I see there is a 404 not found error towards the acme endpoint. 

![image](https://user-images.githubusercontent.com/7556264/127656438-7fc51982-5dd4-4aa0-ae6a-162b709c1333.png)

"https://api.buypass.com/acme/" doesn't exist, but surely it's trying https://api.buypass.com/acme/new-cert or something? I can't really tell

Full error:

Exception while executing function: IssueCertificate Orchestrator function 'IssueCertificate' failed: The activity function 'MergeCertificate' failed: "Failed to deserialize exception from TaskActivity: {"$type":"ACMESharp.Protocol.AcmeProtocolException, ACMESharp","ProblemType":0,"ProblemTypeRaw":null,"ProblemDetail":null,"ProblemStatus":-1,"StackTrace":"   at ACMESharp.Protocol.AcmeProtocolClient.SendAcmeAsync(Uri uri, HttpMethod method, Object message, HttpStatusCode[] expectedStatuses, Boolean skipNonce, Boolean skipSigning, Boolean includePublicKey, CancellationToken cancel, String opName)\r\n   at ACMESharp.Protocol.AcmeProtocolClient.GetOrderDetailsAsync(String orderUrl, OrderDetails existing, CancellationToken cancel)\r\n   at KeyVault.Acmebot.Functions.SharedActivity.MergeCertificate(ValueTuple`2 input) in /home/runner/work/keyvault-acmebot/keyvault-acmebot/KeyVault.Acmebot/Functions/SharedActivity.cs:line 393\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync(Object instance, Object[] arguments) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionInvoker.cs:line 52\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeWithTimeoutAsync(IFunctionInvoker invoker, ParameterHelper parameterHelper, CancellationTokenSource timeoutTokenSource, CancellationTokenSource functionCancellationTokenSource, Boolean throwOnTimeout, TimeSpan timerInterval, IFunctionInstance instance) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs:line 555\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs:line 501\r\n   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\\projects\\azure-webjobs-sdk-rqm4t\\src\\Microsoft.Azure.WebJobs.Host\\Executors\\FunctionExecutor.cs:line 279","Message":"Unexpected response status code [NotFound] for [GetOrderDetailsAsync]","Data":{"$type":"System.Collections.ListDictionaryInternal, System.Private.CoreLib"},"InnerException":null,"HelpLink":null,"Source":"ACMESharp","HResult":-2146233088}". See the function execution logs for additional details.

**Comment by shibayan** [comment] 2021-07-30 13:50
@NikolaiKleppe Thanks for the report.

I got the same error when using Buypass in my environment and was able to identify the cause. This bug will be fixed soon.

**Closed** 2021-07-30 14:18 UTC
Labels: bug

**Comment by shibayan** [comment] 2021-07-30 14:34
This issue has been fixed in `v3.6.4`.

**Comment by NikolaiKleppe** [comment] 2021-07-30 18:27
Thanks for the quick update/fix!
