### ISSUE TITLE
Missing Intermediate Certificate

### ISSUE THREAD

**Issue by bennofication** [shibayan/keyvault-acmebot#355] opened 2021-09-01 10:53 UTC
**Describe the bug**
When adding new certificates, the main intermediate certificate (R3 signed by ISRG X1 Root CA) is not added to the chain, preventing certain client software from building a complete chain of trust.

Example: (note the "extra download" on the intermediate cert on path #2)
![missing_intermediate_certificate](https://user-images.githubusercontent.com/7251115/131659352-76d1e7f9-2f68-4b62-9019-6d62e5413fa2.png)

**Environment (please complete the following information):**
 - Certificate Type: Sub-domain
 - Certificate Deploy Target: Azure API-Management

**Comment by shibayan** [comment] 2021-09-01 11:16
Let's Encrypt is cross-signed in a complicated way due to the expiration of the old root certificate, which is why it looks like this on Qualys.

https://letsencrypt.org/certificates/
https://community.letsencrypt.org/t/providing-a-longer-certificate-chain-by-default/148738

In general, only one chain is included in a certificate, so if you need the complete chain for `ISRG Root X1`, add the `Acmebot:PreferredChain` = `ISRG Root X1` to App Settings.

**Comment by bennofication** [comment] 2021-09-07 08:37
@shibayan Thanks for the info regarding the chain. I removed the certificate from the key vault and generated a new one.

When I download the .pfx file from key vault directly, everything looks ok. The bundle includes two certificates
1. Leaf certificate for my domain
2. Intermediate certificate (R3) signed by LetsEncrypt ISRG X1 Root certificate

But when I access the domain (openssl on terminal, Qualys or Browser), I get a DIFFERENT intermediate certificate (signed not by ISRG X1 but by the old DSG CA X3) 🤔 

Do you have any idea why that would be happening? Is APIM somehow swapping the intermediate cert?

**Comment by shibayan** [comment] 2021-09-07 08:50
I don't know what caused it, but when I uploaded a certificate with `ISRG Root X1` as the root against Front Door, the server sent the old `DST Root CA X3` as well.

The PFX downloaded from Key Vault does not contain the intermediate certificate of `DST Root CA X3`, so it seems that APIM and Front Door are replacing the intermediate certificate by themselves.

Since the `DST Root CA X3` expires on 9/30, I believe that the correct chain will be used after that.

**Comment by bennofication** [comment] 2021-09-07 09:01
@shibayan A client accessing our APIM is pinning a Root CA and I obviously don't want to provide the `DST Root CA X3` due to the expiration.
I'm in contact with Azure technical support (by now escalated to an SME (Subject Matter Expert)) regarding the wrong intermediate certificate and will update this thread if/when I get this thing resolved.

Otherwise: I'll pray things just "work" on 9/30 🙏

**Comment by arkintz** [comment] 2021-09-10 15:54
@bennofication I was staring down the same issue with certificates issued to several WAF_v2 instances and App Services, I just did some tests and found that with the date set to current the trust chain gets displayed back to the DST X3. If I set the date forward to Oct 1 the trust chain shows chained back to the new R3 -> ISRG X1 and continues to display as valid. 

Will be curious to see what the Azure SME has to say but I think we're ok here.

**Comment by shibayan** [comment] 2021-09-30 00:13
I have confirmed that the old intermediate certificate `R3` has expired and has been replaced by the new `ISRG Root X1`, which is also correctly recognized by Qualys.

![image](https://user-images.githubusercontent.com/1356444/135365085-6aca3d8b-f51f-41a2-8ea2-3fbeaea0e67a.png)

![image](https://user-images.githubusercontent.com/1356444/135365144-17d3ff02-765e-4b53-b51b-95d51478a1e2.png)

@bennofication If everything is OK with APIM, please close it.

**Comment by arkintz** [comment] 2021-09-30 00:18
@shibayan I am in the middle of fighting with this at the moment. We have certs deployed across all of our development environments and our production environment, all went down about 5 hours ago. 

It is used both on APIM and also App Gateway WAF frontend (sitting in front of APIM, with the two in private vnet). While APIM shows it as valid in it's custom domain configuration and the App Gateway WAF Frontend is serving publicly as valid, it views the Backend Pool certificate on APIM as invalid/expired.

I have tried telling App Gateway to specifically use the new ISRG Root X1 CA instead of "Well Known CAs", then it just says the backend server certificate does not match the root certificate. Working with our CSP and hopefully getting a line open to Azure App Gateway team.

**Comment by shibayan** [comment] 2021-09-30 00:29
@arkintz It seems to be an Application Gateway issue, so I can't help, but note that the default certificate chain contains an expired `DST Root CA X3` (long-chain). If you are not targeting older Android (e.g. for backend communication), a "short-chain" with `ISRG Root X1` as the root is probably better.

https://letsencrypt.org/certificates/

**Comment by arkintz** [comment] 2021-09-30 01:39
@shibayan correction to previous statement, not all of our environments are broken. We had a few that went down and stayed, a few that went down and seemingly recovered without any intervention and a few that never saw the problem (yet). 

The `ISRG Root X1` is what we tried using, when I forced App Gateway to use that as the CA it complained the CA didnt match the Server Certificate. 

For the moment we've worked around it and have our CSP getting a ticket open, all parties agree it seems to be an App Gateway issue. Wondering if App Gateway will roll over and start working sometime tomorrow (30th) when the root expiration takes place.

**Comment by arkintz** [comment] 2021-10-01 10:43
@shibayan still no answer from MS but all affected app gateways have resumed normal function, recognizing the cert as valid again. Not sure if MS updated or recycled the underlying infrastructure but it seems they now see the cert as having a valid trust chain.

**Comment by shibayan** [comment] 2021-10-05 18:17
There seemed to be some service-dependent issues, but the Acmebot certificate seemed to be fine, so I'm closing it. Thanks everyone.

**Closed** 2021-10-05 18:17 UTC
Labels: bug

**Comment by bennofication** [comment] 2021-10-06 06:00
@shibayan I had a video call with the SME (Subject Matter Expert) at Microsoft and provided them with logs. So far he could only find out that the serverless "consumption" variant of APIM was affected while the traditional "developer" variant worked fine. They are still investigating this but it's going to be quite hard to verify now that the offending CA cert has expired 🤷
