### ISSUE TITLE
Principal not found

### ISSUE THREAD

**Issue by mplogas** [shibayan/keyvault-acmebot#449] opened 2022-01-27 12:08 UTC
**Describe the bug**
When deploying to Azure (public) the role assignment step fails with the error message "Principal not found - Principal <principal id> does not exist in the directory <directory id>"

**To Reproduce**
1. Select Deploy to Azure
2. Put required information into template (create with keyvault: true)
3. start deployment

**Environment (please complete the following information):**
 - Azure Public
 - Certificate Deploy Target: KeyVault

**Comment by shibayan** [comment] 2022-01-27 12:26
To check if the problem is reproducible, I deployed from Deploy to Azure Button as well, and it completed successfully.

Since Azure AD creates Principals asynchronously, it may fail to check for their existence when setting RBAC. This can be fixed by manually adding the RBAC settings.

**Closed by shibayan** 2022-01-27 12:26 UTC
Labels: bug
